// MXMemorialSerializer.h — Persistence Module Version 1.0
// Created: 2026-02-24
// Agent 10: Persistence
// Consumers: MXSaveManager (internal to Persistence module), UI (Memorial Wall screen)
// Change Log:
//   v1.0 — Initial implementation: memorial wall with visual state archiving after 500 entries

#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "MXRobotProfile.h"
#include "MXEventData.h"
#include "MXMemorialSerializer.generated.h"

// ---------------------------------------------------------------------------
// Memorial Entry
// ---------------------------------------------------------------------------

/**
 * FMXMemorialEntry
 * Permanent record of a fallen robot.
 * Grows unbounded as robots die. Visual state is pruned after 500 entries,
 * but the robot's name, eulogy, and death message are preserved forever.
 */
USTRUCT(BlueprintType)
struct MICROEXODUS_API FMXMemorialEntry
{
    GENERATED_BODY()

    /** Full robot profile snapshot captured at the moment of death or sacrifice. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FMXRobotProfile ProfileSnapshot;

    /** The DEMS event record that ended this robot's life. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FMXEventData DeathEvent;

    /** Short eulogy generated by the Reports module. Preserved forever. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Eulogy;

    /** 1-indexed run number during which this robot died. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 RunNumber = 0;

    /** 1-indexed level number within the run where death occurred. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 LevelNumber = 0;

    /** Real-world wall-clock time of death. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FDateTime DateOfDeath = FDateTime::MinValue();

    /** True if this robot chose sacrifice; false for an involuntary death. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bWasSacrifice = false;

    /**
     * Display names of robots saved by this sacrifice (populated only when bWasSacrifice is true).
     * Up to 3 names shown on the Memorial Wall.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FString> RobotsSaved;

    /**
     * True once ArchiveOldEntries has pruned this entry's visual_evolution_state.
     * UI should show a "visual data archived" placeholder for these entries.
     */
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bVisualStateArchived = false;
};

// ---------------------------------------------------------------------------
// UMXMemorialSerializer
// ---------------------------------------------------------------------------

/**
 * UMXMemorialSerializer
 * Manages the Memorial Wall — a permanent, ever-growing record of every robot that has
 * ever been lost, in any run.
 *
 * Archiving policy:
 *   - Entries 0 through (Total - KeepFullCount - 1) are "archived":
 *     their visual_evolution_state is zeroed out and bVisualStateArchived is set.
 *   - Everything else (robot name, death message, eulogy, run/level numbers) is NEVER pruned.
 *     A player should always be able to find their first robot's name and how it died.
 *
 * Usage:
 *   - AddToMemorial() is called by whoever handles OnRobotDied / OnRobotSacrificed
 *     (typically from a listener on the persistent game state).
 *   - Serialize/Deserialize is called by MXSaveManager.
 */
UCLASS()
class MICROEXODUS_API UMXMemorialSerializer : public UObject
{
    GENERATED_BODY()

public:

    // -------------------------------------------------------------------------
    // Memorial Serialization
    // -------------------------------------------------------------------------

    /**
     * Serialize the entire memorial array to the archive.
     *
     * @param Ar       FArchive opened for writing.
     * @param Entries  The full memorial array (may be thousands of entries).
     */
    void SerializeMemorial(FArchive& Ar, const TArray<FMXMemorialEntry>& Entries);

    /**
     * Deserialize the memorial array from the archive.
     *
     * @param Ar  FArchive opened for reading.
     * @return    Full array of memorial entries in chronological order.
     */
    TArray<FMXMemorialEntry> DeserializeMemorial(FArchive& Ar);

    // -------------------------------------------------------------------------
    // Entry Management
    // -------------------------------------------------------------------------

    /**
     * Add a newly-dead robot to the memorial.
     * Called immediately after death/sacrifice is confirmed.
     *
     * @param Memorial     The in-memory memorial array to append to.
     * @param DeadRobot    Full profile snapshot captured at time of death.
     * @param DeathEvent   The DEMS event that killed this robot.
     * @param Eulogy       Eulogy string from ReportNarrator.
     * @param RunNumber    Current run number (1-indexed).
     * @param LevelNumber  Current level number (1-indexed).
     * @param bSacrifice   True if this was a voluntary sacrifice.
     * @param SavedRobots  Names of robots saved (only meaningful if bSacrifice is true).
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Persistence|Memorial")
    void AddToMemorial(
        TArray<FMXMemorialEntry>& Memorial,
        const FMXRobotProfile&    DeadRobot,
        const FMXEventData&       DeathEvent,
        const FString&            Eulogy,
        int32                     RunNumber,
        int32                     LevelNumber,
        bool                      bSacrifice,
        const TArray<FString>&    SavedRobots);

    /**
     * Archive old entries once the memorial exceeds KeepFullCount.
     * Zeroes out visual_evolution_state for all but the most recent KeepFullCount entries.
     * Sets bVisualStateArchived = true on pruned entries.
     *
     * @param Memorial        The memorial array to archive in-place.
     * @param KeepFullCount   How many recent entries to leave with full visual state (default: 500).
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Persistence|Memorial")
    void ArchiveOldEntries(TArray<FMXMemorialEntry>& Memorial, int32 KeepFullCount = 500);

    // -------------------------------------------------------------------------
    // Lookup
    // -------------------------------------------------------------------------

    /**
     * Find an entry by robot GUID.
     *
     * @param Memorial  The array to search.
     * @param RobotId   The robot GUID to locate.
     * @return          Pointer to the matching entry, or nullptr if not found.
     */
    // Not Blueprint-exposed: UHT forbids UFUNCTION returning USTRUCT*.
    FMXMemorialEntry* GetMemorialEntry(TArray<FMXMemorialEntry>& Memorial, const FGuid& RobotId);

private:

    /** Serialize a single memorial entry. Uses block-size prefix for forward compatibility. */
    void SerializeEntry(FArchive& Ar, const FMXMemorialEntry& Entry);

    /** Deserialize a single memorial entry. */
    FMXMemorialEntry DeserializeEntry(FArchive& Ar);
};
