// MXRobotFactory.h — Robot Factory Module v1.0
// Created: 2026-03-01
// Agent 14: Robot Factory
// The lobby/factory system that generates recruit pools between levels.
//
// Pre-level flow:
//   1. Level ends → survivors and rescued robots carry over
//   2. Factory generates fresh recruits to fill pool
//   3. Player reviews pool in the lobby UI, selects up to 5 for the mission
//   4. (Optional) Player enters a friend's code at the Code Terminal
//   5. (Optional) Player applies cosmetic parts at the Workshop
//   6. Player confirms selection → mission begins
//
// Pool composition:
//   Survivors         — robots that completed the previous level
//   Rescued           — robots rescued during the previous level
//   Fresh recruits    — 1–5 new robots generated by the factory
//                       (count depends on difficulty + BatchSize upgrade)
//   Code replicas     — replicated from entered codes (requires CodeTerminal upgrade)
//
// Mission cap is always 5 robots. Pool can be larger than 5 (player chooses).
//
// Change Log:
//   v1.0 — Initial implementation

#pragma once

#include "CoreMinimal.h"
#include "MXRobotFactoryData.h"
#include "MXRobotCodec.h"
#include "MXRobotFactory.generated.h"

// Forward declarations
class UMXRobotManager;
class UMXRobotAssembler;
class UMXNameGenerator;
class UMXPersonalityGenerator;

// ---------------------------------------------------------------------------
// Delegates
// ---------------------------------------------------------------------------

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(
    FOnLobbyPoolReady,
    const FMXLobbyPool&, Pool);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(
    FOnCodeRedeemed,
    const FString&, Code,
    const FMXRecruitCandidate&, Replica);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(
    FOnCodeRejected,
    const FString&, Code,
    const FString&, Reason);

DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(
    FOnUpgradePurchased,
    EFactoryUpgrade, Upgrade,
    int32, NewLevel);

// ---------------------------------------------------------------------------
// UMXRobotFactory
// ---------------------------------------------------------------------------

/**
 * UMXRobotFactory
 * Manages the pre-level lobby: pool generation, selection, codes, upgrades.
 *
 * Lifecycle per level:
 *   1. RunManager calls BuildLobbyPool(Survivors, Rescued, LevelNumber, Tier)
 *   2. Factory adds fresh recruits based on difficulty + upgrades
 *   3. OnLobbyPoolReady fires → UI displays the pool
 *   4. Player interacts: selects robots, enters codes, buys upgrades
 *   5. Player confirms → GetSelectedRobots() returns the final 5
 *   6. RunManager creates the robots via RobotManager and starts the level
 */
UCLASS(BlueprintType, Blueprintable)
class MICROEXODUS_API UMXRobotFactory : public UObject
{
    GENERATED_BODY()

public:

    UMXRobotFactory();

    // -------------------------------------------------------------------------
    // Initialisation
    // -------------------------------------------------------------------------

    /**
     * Wire up dependencies. Call once from GameInstance::Init.
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Factory")
    void Initialize(
        UMXRobotManager*         InRobotManager,
        UMXRobotAssembler*       InAssembler,
        UMXNameGenerator*        InNameGenerator,
        UMXPersonalityGenerator* InPersonalityGenerator);

    /**
     * Load persistent factory state (from save data).
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Factory")
    void LoadFactoryState(const FMXFactoryState& State);

    /**
     * Get current factory state for saving.
     */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "MX|Factory")
    FMXFactoryState GetFactoryState() const { return FactoryState; }

    // -------------------------------------------------------------------------
    // Lobby Pool Generation
    // -------------------------------------------------------------------------

    /**
     * Build the lobby recruit pool for the next level.
     *
     * @param SurvivorIds    GUIDs of robots that survived the previous level.
     * @param RescuedIds     GUIDs of robots rescued during the previous level.
     * @param LevelNumber    The upcoming level (1–20). Level 1 = run start.
     * @param Tier           Current run difficulty tier.
     * @param PendingSalvage Salvage drops from the previous level.
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Factory")
    void BuildLobbyPool(
        const TArray<FGuid>&         SurvivorIds,
        const TArray<FGuid>&         RescuedIds,
        int32                        LevelNumber,
        ETier                        Tier,
        const TArray<FMXSalvageDrop>& PendingSalvage);

    /**
     * Get the current lobby pool.
     */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "MX|Factory")
    const FMXLobbyPool& GetLobbyPool() const { return CurrentPool; }

    // -------------------------------------------------------------------------
    // Selection
    // -------------------------------------------------------------------------

    /**
     * Toggle a candidate's selection state. Enforces the 5-robot cap.
     * @return True if the toggle succeeded.
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Factory")
    bool ToggleCandidateSelection(const FGuid& RobotId);

    /**
     * Auto-select up to MaxSelectable robots. Prioritises survivors > rescued > recruits.
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Factory")
    void AutoSelectBest();

    /**
     * Get GUIDs of all currently selected candidates.
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Factory")
    TArray<FGuid> GetSelectedRobots() const;

    /**
     * Get the count of currently selected candidates.
     */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "MX|Factory")
    int32 GetSelectedCount() const;

    // -------------------------------------------------------------------------
    // Robot Code System
    // -------------------------------------------------------------------------

    /**
     * Get the shareable code for a robot by GUID.
     * Works for any robot that has been through the factory.
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Factory|Code")
    FString GetRobotCode(const FGuid& RobotId) const;

    /**
     * Attempt to redeem a friend's robot code.
     * Requirements:
     *   - CodeTerminal upgrade must be purchased (level >= 1)
     *   - Code must be syntactically valid
     *   - Code must not have been redeemed before
     *   - Player must have the required cosmetic parts unlocked
     *     (OR the factory must have RecruitDiversity >= 3)
     *
     * On success: creates a CodeReplica candidate and adds to the lobby pool.
     * @param CodeString  The code entered by the player.
     * @return            True if redeemed successfully.
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Factory|Code")
    bool RedeemCode(const FString& CodeString);

    // -------------------------------------------------------------------------
    // Upgrades
    // -------------------------------------------------------------------------

    /**
     * Check if an upgrade can be purchased (enough salvage, not maxed).
     */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "MX|Factory")
    bool CanPurchaseUpgrade(EFactoryUpgrade Upgrade) const;

    /**
     * Purchase an upgrade. Deducts salvage parts.
     * @return True if purchased.
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Factory")
    bool PurchaseUpgrade(EFactoryUpgrade Upgrade);

    /**
     * Get the current level of a specific upgrade.
     */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "MX|Factory")
    int32 GetUpgradeLevel(EFactoryUpgrade Upgrade) const;

    // -------------------------------------------------------------------------
    // Salvage
    // -------------------------------------------------------------------------

    /**
     * Add salvage parts currency (from level completion rewards).
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Factory")
    void AddSalvageParts(int32 Amount);

    /**
     * Process salvage drops: unlock new cosmetics, convert rest to currency.
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Factory")
    void ProcessSalvageDrops(const TArray<FMXSalvageDrop>& Drops);

    /**
     * Check if a specific cosmetic part ID is unlocked.
     */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "MX|Factory")
    bool IsPartUnlocked(const FString& PartId) const;

    // -------------------------------------------------------------------------
    // Queries
    // -------------------------------------------------------------------------

    /**
     * Get the current salvage parts balance.
     */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "MX|Factory")
    int32 GetSalvageParts() const { return FactoryState.SalvageParts; }

    /**
     * How many fresh recruits will be generated for a given level/tier.
     */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "MX|Factory")
    int32 GetFreshRecruitCount(int32 LevelNumber, ETier Tier) const;

    /**
     * Check if the Code Terminal is available.
     */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "MX|Factory")
    bool IsCodeTerminalUnlocked() const;

    /**
     * Check if the Cosmetic Workshop is available.
     */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "MX|Factory")
    bool IsCosmeticWorkshopUnlocked() const;

    // -------------------------------------------------------------------------
    // Delegates
    // -------------------------------------------------------------------------

    UPROPERTY(BlueprintAssignable, Category = "MX|Factory")
    FOnLobbyPoolReady OnLobbyPoolReady;

    UPROPERTY(BlueprintAssignable, Category = "MX|Factory")
    FOnCodeRedeemed OnCodeRedeemed;

    UPROPERTY(BlueprintAssignable, Category = "MX|Factory")
    FOnCodeRejected OnCodeRejected;

    UPROPERTY(BlueprintAssignable, Category = "MX|Factory")
    FOnUpgradePurchased OnUpgradePurchased;

private:

    // -------------------------------------------------------------------------
    // References
    // -------------------------------------------------------------------------

    UPROPERTY()
    TObjectPtr<UMXRobotManager> RobotManager;

    UPROPERTY()
    TObjectPtr<UMXRobotAssembler> Assembler;

    UPROPERTY()
    TObjectPtr<UMXNameGenerator> NameGenerator;

    UPROPERTY()
    TObjectPtr<UMXPersonalityGenerator> PersonalityGenerator;

    // -------------------------------------------------------------------------
    // State
    // -------------------------------------------------------------------------

    /** Persistent factory state (upgrades, currency, unlocks). */
    FMXFactoryState FactoryState;

    /** Current lobby pool for this level transition. */
    FMXLobbyPool CurrentPool;

    // -------------------------------------------------------------------------
    // Internal
    // -------------------------------------------------------------------------

    /** Generate fresh recruit candidates. */
    TArray<FMXRecruitCandidate> GenerateFreshRecruits(int32 Count, int32 LevelNumber);

    /** Create a single fresh recruit with deterministic seeding. */
    FMXRecruitCandidate CreateFreshRecruit(int32 RecruitIndex, int32 LevelNumber);

    /** Create a candidate from an existing robot profile (survivor/rescued). */
    FMXRecruitCandidate CreateCandidateFromProfile(const FGuid& RobotId, ERecruitSource Source);

    /** Create a replica candidate from a decoded robot code. */
    FMXRecruitCandidate CreateReplicaFromCode(const FMXRobotCode& Code);

    /** Initialise default upgrade levels if state is empty. */
    void EnsureUpgradesInitialised();

    /** Look up an upgrade entry (mutable). Returns nullptr if not found. */
    FMXFactoryUpgradeLevel* FindUpgrade(EFactoryUpgrade Upgrade);

    /** Look up an upgrade entry (const). Returns nullptr if not found. */
    const FMXFactoryUpgradeLevel* FindUpgrade(EFactoryUpgrade Upgrade) const;

    /** Compute upgrade cost for a given upgrade type and level. */
    static int32 ComputeUpgradeCost(EFactoryUpgrade Upgrade, int32 CurrentLevel);
};
