// MXRoomGenerator.h — Procedural Generation Module v1.0
// Created: 2026-03-01
// Agent 12: Procedural Generation
// Generates room layouts for a single level: room count, types, sizes,
// connectivity graph, and critical path from entrance to exit.
// Deterministic: same seed + level number = same room layout.
//
// Change Log:
//   v1.0 — Initial implementation

#pragma once

#include "CoreMinimal.h"
#include "MXTypes.h"
#include "MXProceduralData.h"
#include "MXRoomGenerator.generated.h"

// ---------------------------------------------------------------------------
// UMXRoomGenerator
// ---------------------------------------------------------------------------

/**
 * UMXRoomGenerator
 * Produces room definitions for a single level.
 *
 * Room count scales with level number:
 *   Levels  1–5  : 4–6 rooms  (introductory)
 *   Levels  6–10 : 6–8 rooms  (developing)
 *   Levels 11–15 : 7–10 rooms (complex)
 *   Levels 16–20 : 8–12 rooms (climactic)
 *
 * Every level always has exactly one Entrance and one Exit room.
 * A critical path is guaranteed from Entrance → Exit.
 * Sacrifice gates appear on levels 5, 10, 15, and 20.
 */
UCLASS(BlueprintType, Blueprintable)
class MICROEXODUS_API UMXRoomGenerator : public UObject
{
    GENERATED_BODY()

public:

    UMXRoomGenerator();

    // -------------------------------------------------------------------------
    // Generation
    // -------------------------------------------------------------------------

    /**
     * Generate a complete room layout for one level.
     * @param LevelSeed     Deterministic seed for this specific level.
     * @param LevelNumber   1-indexed level number (1–20).
     * @param Tier          Difficulty tier (affects room count at high tiers).
     * @return              Array of FMXRoomDef describing the level's rooms.
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Procedural|Rooms")
    TArray<FMXRoomDef> GenerateRooms(int64 LevelSeed, int32 LevelNumber, ETier Tier);

    /**
     * Compute the critical path from Entrance to Exit using the connectivity graph.
     * Returns an ordered array of room indices.
     * @param Rooms  The room array generated by GenerateRooms.
     * @return       Ordered room indices forming the shortest path.
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Procedural|Rooms")
    TArray<int32> ComputeCriticalPath(const TArray<FMXRoomDef>& Rooms);

    /**
     * Determine which room index should contain the sacrifice gate for this level.
     * Returns -1 if the level doesn't have a gate (only levels 5, 10, 15, 20 do).
     * @param Rooms         The room array.
     * @param LevelNumber   1-indexed level number.
     * @param LevelSeed     For deterministic selection among candidates.
     * @return              Room index of the gate room, or -1 if none.
     */
    UFUNCTION(BlueprintCallable, Category = "MX|Procedural|Rooms")
    int32 PickGateRoom(const TArray<FMXRoomDef>& Rooms, int32 LevelNumber, int64 LevelSeed);

private:

    /**
     * Get the room count range [Min, Max] for a given level band.
     * Higher tiers increase both ends of the range.
     */
    void GetRoomCountRange(int32 LevelNumber, ETier Tier, int32& OutMin, int32& OutMax) const;

    /**
     * Pick a room type appropriate for the room's position in the sequence.
     * @param RoomIndex     Index within the level (0 = entrance, last = exit).
     * @param RoomCount     Total rooms in the level.
     * @param LevelNumber   For difficulty-driven type weighting.
     * @param Stream        Seeded RNG stream.
     * @return              The chosen room type.
     */
    ERoomType PickRoomType(int32 RoomIndex, int32 RoomCount, int32 LevelNumber, FRandomStream& Stream) const;

    /**
     * Compute room dimensions based on type.
     * @param RoomType  The archetype.
     * @param Stream    Seeded RNG for variation within type bounds.
     * @return          Size (X = width, Y = length) in cm.
     */
    FVector2D ComputeRoomSize(ERoomType RoomType, FRandomStream& Stream) const;

    /**
     * Compute max hazard slots for a given room type.
     */
    int32 GetMaxHazardSlots(ERoomType RoomType) const;

    /**
     * Build the connectivity graph: each room connects to at least one neighbor.
     * Ensures a connected graph with a valid path from room 0 to the last room.
     */
    void BuildConnectivity(TArray<FMXRoomDef>& Rooms, FRandomStream& Stream) const;

    /**
     * Assign world offsets to rooms so they form a linear-ish sequence with some branching.
     */
    void AssignWorldOffsets(TArray<FMXRoomDef>& Rooms, FRandomStream& Stream) const;
};
