// MXRunReportUI.cpp — UI Module v1.0
// Created: 2026-02-22
// Agent 11: UI

#include "MXRunReportUI.h"
#include "Blueprint/WidgetTree.h"
#include "Components/TextBlock.h"
#include "Components/Border.h"
#include "Components/VerticalBox.h"
#include "Components/HorizontalBox.h"
#include "Components/ScrollBox.h"
#include "Components/Button.h"
#include "Kismet/GameplayStatics.h"

// ---------------------------------------------------------------------------
// NativeConstruct / NativeDestruct
// ---------------------------------------------------------------------------

void UMXRunReportUI::NativeConstruct()
{
    Super::NativeConstruct();

    if (ContinueButton)
    {
        ContinueButton->SetVisibility(ESlateVisibility::Collapsed);
        ContinueButton->OnClicked.AddDynamic(this, &UMXRunReportUI::OnContinueClicked);
    }

    if (ShareButton)
    {
        ShareButton->OnClicked.AddDynamic(this, &UMXRunReportUI::OnShareClicked);
    }

    if (FullLogButton)
    {
        FullLogButton->OnClicked.AddDynamic(this, &UMXRunReportUI::OnFullLogClicked);
    }

    if (FullEventLogScrollBox)
    {
        FullEventLogScrollBox->SetVisibility(ESlateVisibility::Collapsed);
    }
}

void UMXRunReportUI::NativeDestruct()
{
    if (GetWorld())
    {
        GetWorld()->GetTimerManager().ClearTimer(TypewriterTimer);
        GetWorld()->GetTimerManager().ClearTimer(StatCounterTimer);
        GetWorld()->GetTimerManager().ClearTimer(AwardRevealTimer);
        GetWorld()->GetTimerManager().ClearTimer(DeathRevealTimer);
        GetWorld()->GetTimerManager().ClearTimer(SacrificeRevealTimer);
    }
    Super::NativeDestruct();
}

// ---------------------------------------------------------------------------
// Master Entry Point
// ---------------------------------------------------------------------------

void UMXRunReportUI::DisplayReport(const FMXRunReport& Report)
{
    CachedReport = Report;

    ShowHeader(Report.run_data);
    PlayOpeningNarrative(Report.opening_narrative);
    ShowNumbers(Report.run_data);
    ShowHatCensus(Report.hat_census, TArray<FString>());  // Commentary generated by DEMS; pass empty if none
    ShowLevelBreakdown(Report.run_data);
    ShowHighlights(Report.highlights);
    ShowAwards(Report.awards);
    ShowDeathRoll(Report.death_roll);
    ShowSacrificeHonorRoll(Report.sacrifice_honor_roll);
    PlayClosingNarrative(Report.closing_narrative);

    // Build section tab bar
    if (SectionTabBar && WidgetTree)
    {
        SectionTabBar->ClearChildren();
        const TArray<FString> TabLabels = {
            TEXT("Header"), TEXT("Opening"), TEXT("Numbers"), TEXT("Hats"),
            TEXT("Levels"), TEXT("Highlights"), TEXT("Awards"),
            TEXT("Deaths"), TEXT("Sacrifices"), TEXT("Closing")
        };
        for (int32 i = 0; i < TabLabels.Num(); ++i)
        {
            UWidget* Tab = BuildTabButton(i, TabLabels[i]);
            if (Tab) SectionTabBar->AddChild(Tab);
        }
    }

    NavigateToSection(MXReportSection::Opening);
}

// ---------------------------------------------------------------------------
// Section: Header
// ---------------------------------------------------------------------------

void UMXRunReportUI::ShowHeader(const FMXRunData& RunData)
{
    if (RunNumberText)
    {
        RunNumberText->SetText(FText::FromString(
            FString::Printf(TEXT("Run #%d"), RunData.run_number)));
    }

    if (OutcomeText)
    {
        const bool bSuccess = (RunData.outcome == ERunOutcome::Success);
        OutcomeText->SetText(FText::FromString(bSuccess ? TEXT("SURVIVED") : TEXT("FAILED")));
        OutcomeText->SetColorAndOpacity(FSlateColor(bSuccess
            ? FLinearColor(0.1f, 0.9f, 0.2f, 1.0f)
            : FLinearColor(0.9f, 0.1f, 0.1f, 1.0f)));
    }

    if (DurationText && RunData.end_time > RunData.start_time)
    {
        const float DurationSecs = (float)(RunData.end_time - RunData.start_time).GetTotalSeconds();
        DurationText->SetText(FText::FromString(FormatDuration(DurationSecs)));
    }

    if (HeaderPanel && WidgetTree)
    {
        // Tier + modifiers row
        const UEnum* TierEnum = StaticEnum<ETier>();
        const FString TierStr = TierEnum
            ? TierEnum->GetNameStringByValue((int64)RunData.tier)
            : TEXT("Standard");

        UTextBlock* TierText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
        if (TierText)
        {
            TierText->SetText(FText::FromString(FString::Printf(TEXT("Tier: %s"), *TierStr)));
            HeaderPanel->AddChild(TierText);
        }

        if (!RunData.active_modifiers.IsEmpty())
        {
            UTextBlock* ModText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
            if (ModText)
            {
                const FString ModStr = FString::Join(RunData.active_modifiers, TEXT(", "));
                ModText->SetText(FText::FromString(FString::Printf(TEXT("Modifiers: %s"), *ModStr)));
                HeaderPanel->AddChild(ModText);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Section: Opening Narrative (typewriter)
// ---------------------------------------------------------------------------

void UMXRunReportUI::PlayOpeningNarrative(const FString& Text)
{
    if (!OpeningNarrativeText || Text.IsEmpty()) return;

    TypewriterFullText    = Text;
    TypewriterCharIndex   = 0;
    bTypewriterClosing    = false;

    OpeningNarrativeText->SetText(FText::FromString(TEXT("")));

    const float TickInterval = (TypewriterCPS > 0.0f) ? (1.0f / TypewriterCPS) : 0.025f;

    if (GetWorld())
    {
        GetWorld()->GetTimerManager().SetTimer(
            TypewriterTimer,
            this, &UMXRunReportUI::TypewriterTick,
            TickInterval, true);
    }
}

void UMXRunReportUI::TypewriterTick()
{
    if (!OpeningNarrativeText) return;

    if (TypewriterCharIndex >= TypewriterFullText.Len())
    {
        if (GetWorld()) GetWorld()->GetTimerManager().ClearTimer(TypewriterTimer);

        if (bTypewriterClosing)
        {
            // Show continue button after delay
            if (GetWorld())
            {
                FTimerHandle DelayHandle;
                GetWorld()->GetTimerManager().SetTimer(DelayHandle, [this]()
                {
                    if (ContinueButton)
                    {
                        ContinueButton->SetVisibility(ESlateVisibility::Visible);
                    }
                    OnClosingNarrativeComplete();
                }, ContinueDelay, false);
            }
        }
        else
        {
            OnOpeningNarrativeComplete();
        }
        return;
    }

    ++TypewriterCharIndex;
    const FString Current = TypewriterFullText.Left(TypewriterCharIndex);
    OpeningNarrativeText->SetText(FText::FromString(Current));
}

// ---------------------------------------------------------------------------
// Section: Numbers (animated counters)
// ---------------------------------------------------------------------------

void UMXRunReportUI::ShowNumbers(const FMXRunData& RunData)
{
    if (!NumbersPanel || !WidgetTree) return;

    NumbersPanel->ClearChildren();
    StatCounters.Empty();

    auto AddStat = [&](const FString& Label, int32 Value)
    {
        UTextBlock* StatText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
        if (!StatText) return;

        StatText->SetText(FText::FromString(FString::Printf(TEXT("%s: 0"), *Label)));
        NumbersPanel->AddChild(StatText);

        FStatCounter Counter;
        Counter.Label   = Label;
        Counter.Current = 0;
        Counter.Target  = Value;
        Counter.Widget  = StatText;
        StatCounters.Add(Counter);
    };

    AddStat(TEXT("Robots Deployed"),  RunData.robots_deployed);
    AddStat(TEXT("Survived"),         RunData.robots_survived);
    AddStat(TEXT("Lost"),             RunData.robots_lost);
    AddStat(TEXT("Rescued"),          RunData.robots_rescued);
    AddStat(TEXT("Levels Completed"), RunData.levels_completed);
    AddStat(TEXT("Final Score"),      RunData.score);

    if (GetWorld() && !StatCounters.IsEmpty())
    {
        GetWorld()->GetTimerManager().SetTimer(
            StatCounterTimer,
            this, &UMXRunReportUI::StatCounterTick,
            StatTickInterval, true);
    }
}

void UMXRunReportUI::StatCounterTick()
{
    bool bAllDone = true;

    for (FStatCounter& Counter : StatCounters)
    {
        if (Counter.Current >= Counter.Target) continue;

        bAllDone = false;
        const int32 Step = FMath::Max(1, (Counter.Target - Counter.Current) / 8);
        Counter.Current   = FMath::Min(Counter.Current + Step, Counter.Target);

        if (Counter.Widget)
        {
            Counter.Widget->SetText(FText::FromString(
                FString::Printf(TEXT("%s: %d"), *Counter.Label, Counter.Current)));
        }

        OnStatCounterTick(Counter.Label, Counter.Current, Counter.Target);
    }

    if (bAllDone && GetWorld())
    {
        GetWorld()->GetTimerManager().ClearTimer(StatCounterTimer);
    }
}

// ---------------------------------------------------------------------------
// Section: Hat Census
// ---------------------------------------------------------------------------

void UMXRunReportUI::ShowHatCensus(const FMXHatCensus& Census, const TArray<FString>& Commentary)
{
    if (!HatCensusPanel || !WidgetTree) return;

    HatCensusPanel->ClearChildren();

    auto AddHatStat = [&](const FString& Label, const FString& Value)
    {
        UWidget* Row = BuildStatRow(Label, Value);
        if (Row) HatCensusPanel->AddChild(Row);
    };

    AddHatStat(TEXT("Hatted Robots"),   FString::FromInt(Census.total_hatted));
    AddHatStat(TEXT("Unique Hats"),     FString::FromInt(Census.unique_hats));
    AddHatStat(TEXT("Most Common Hat"), Census.most_common_hat.IsEmpty() ? TEXT("—") : Census.most_common_hat);
    AddHatStat(TEXT("Rarest Hat"),      Census.rarest_hat.IsEmpty() ? TEXT("—") : Census.rarest_hat);
    AddHatStat(TEXT("Hats Lost"),       FString::FromInt(Census.hats_lost));
    AddHatStat(TEXT("Hat Survival"),
        FString::Printf(TEXT("%.0f%%"), Census.hat_survival_rate * 100.0f));

    // Interleave commentary lines
    for (const FString& Line : Commentary)
    {
        UTextBlock* CommentText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
        if (CommentText)
        {
            CommentText->SetText(FText::FromString(Line));
            CommentText->SetColorAndOpacity(FSlateColor(FLinearColor(0.7f, 0.7f, 0.8f, 1.0f)));
            HatCensusPanel->AddChild(CommentText);
        }
    }
}

// ---------------------------------------------------------------------------
// Section: Level Breakdown
// ---------------------------------------------------------------------------

void UMXRunReportUI::ShowLevelBreakdown(const FMXRunData& RunData)
{
    if (!LevelBreakdownPanel || !WidgetTree) return;

    LevelBreakdownPanel->ClearChildren();
    ExpandedLevels.Empty();

    const int32 MaxLevel = FMath::Max(1, RunData.levels_completed);
    for (int32 L = 1; L <= MaxLevel; ++L)
    {
        TArray<FMXEventData> LevelEvents = GetLevelEvents(RunData, L);
        UWidget* Card = BuildLevelCard(L, LevelEvents);
        if (Card) LevelBreakdownPanel->AddChild(Card);
    }
}

void UMXRunReportUI::ToggleLevelExpanded(int32 LevelNumber)
{
    if (ExpandedLevels.Contains(LevelNumber))
    {
        ExpandedLevels.Remove(LevelNumber);
    }
    else
    {
        ExpandedLevels.Add(LevelNumber);
    }
    // Re-build level breakdown to reflect expansion state
    ShowLevelBreakdown(CachedReport.run_data);
}

// ---------------------------------------------------------------------------
// Section: Highlights
// ---------------------------------------------------------------------------

void UMXRunReportUI::ShowHighlights(const TArray<FMXHighlight>& Highlights)
{
    if (!HighlightsPanel || !WidgetTree) return;

    HighlightsPanel->ClearChildren();

    for (int32 i = 0; i < Highlights.Num(); ++i)
    {
        UWidget* Card = BuildHighlightCard(Highlights[i]);
        if (Card)
        {
            HighlightsPanel->AddChild(Card);
            OnHighlightRevealed(Highlights[i], i);
        }
    }
}

// ---------------------------------------------------------------------------
// Section: Awards (sequential reveal)
// ---------------------------------------------------------------------------

void UMXRunReportUI::ShowAwards(const TArray<FMXAward>& Awards)
{
    if (!AwardsPanel) return;

    AwardsPanel->ClearChildren();
    PendingAwards = Awards;
    AwardRevealIndex = 0;

    if (PendingAwards.IsEmpty()) return;

    // Reveal first immediately, subsequent ones on timer
    RevealNextAward();
}

void UMXRunReportUI::RevealNextAward()
{
    if (!AwardsPanel || AwardRevealIndex >= PendingAwards.Num()) return;

    UWidget* Card = BuildAwardCard(PendingAwards[AwardRevealIndex]);
    if (Card)
    {
        AwardsPanel->AddChild(Card);
        OnAwardRevealed(PendingAwards[AwardRevealIndex], AwardRevealIndex);
    }

    ++AwardRevealIndex;

    if (AwardRevealIndex < PendingAwards.Num() && GetWorld())
    {
        GetWorld()->GetTimerManager().SetTimer(
            AwardRevealTimer, this, &UMXRunReportUI::RevealNextAward,
            AwardRevealInterval, false);
    }
}

// ---------------------------------------------------------------------------
// Section: Death Roll (fade-in)
// ---------------------------------------------------------------------------

void UMXRunReportUI::ShowDeathRoll(const TArray<FMXDeathEntry>& Deaths)
{
    if (!DeathRollPanel) return;

    DeathRollPanel->ClearChildren();
    PendingDeaths = Deaths;
    DeathRevealIndex = 0;

    if (PendingDeaths.IsEmpty())
    {
        if (WidgetTree)
        {
            UTextBlock* NoneText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
            if (NoneText)
            {
                NoneText->SetText(FText::FromString(TEXT("No robots were lost this run.")));
                DeathRollPanel->AddChild(NoneText);
            }
        }
        return;
    }

    RevealNextDeath();
}

void UMXRunReportUI::RevealNextDeath()
{
    if (!DeathRollPanel || DeathRevealIndex >= PendingDeaths.Num()) return;

    UWidget* Card = BuildDeathCard(PendingDeaths[DeathRevealIndex]);
    if (Card)
    {
        DeathRollPanel->AddChild(Card);
        OnDeathEntryRevealed(PendingDeaths[DeathRevealIndex], DeathRevealIndex);
    }

    ++DeathRevealIndex;

    if (DeathRevealIndex < PendingDeaths.Num() && GetWorld())
    {
        GetWorld()->GetTimerManager().SetTimer(
            DeathRevealTimer, this, &UMXRunReportUI::RevealNextDeath,
            DeathRevealInterval, false);
    }
}

// ---------------------------------------------------------------------------
// Section: Sacrifice Honor Roll
// ---------------------------------------------------------------------------

void UMXRunReportUI::ShowSacrificeHonorRoll(const TArray<FMXSacrificeEntry>& Sacrifices)
{
    if (!SacrificePanel) return;

    SacrificePanel->ClearChildren();
    PendingSacrifices    = Sacrifices;
    SacrificeRevealIndex = 0;

    if (PendingSacrifices.IsEmpty()) return;
    RevealNextSacrifice();
}

void UMXRunReportUI::RevealNextSacrifice()
{
    if (!SacrificePanel || SacrificeRevealIndex >= PendingSacrifices.Num()) return;

    UWidget* Card = BuildSacrificeCard(PendingSacrifices[SacrificeRevealIndex]);
    if (Card)
    {
        SacrificePanel->AddChild(Card);
        OnSacrificeEntryRevealed(PendingSacrifices[SacrificeRevealIndex], SacrificeRevealIndex);
    }

    ++SacrificeRevealIndex;

    if (SacrificeRevealIndex < PendingSacrifices.Num() && GetWorld())
    {
        GetWorld()->GetTimerManager().SetTimer(
            SacrificeRevealTimer, this, &UMXRunReportUI::RevealNextSacrifice,
            AwardRevealInterval, false);
    }
}

// ---------------------------------------------------------------------------
// Section: Closing Narrative
// ---------------------------------------------------------------------------

void UMXRunReportUI::PlayClosingNarrative(const FString& Text)
{
    if (!ClosingNarrativeText || Text.IsEmpty()) return;

    bTypewriterClosing  = true;
    TypewriterFullText  = Text;
    TypewriterCharIndex = 0;

    ClosingNarrativeText->SetText(FText::FromString(TEXT("")));

    const float TickInterval = (TypewriterCPS > 0.0f) ? (1.0f / TypewriterCPS) : 0.025f;

    if (GetWorld())
    {
        // Clear any running opening typewriter
        GetWorld()->GetTimerManager().ClearTimer(TypewriterTimer);
        // Reuse same timer but now routing to ClosingNarrativeText
        GetWorld()->GetTimerManager().SetTimer(
            TypewriterTimer, this, &UMXRunReportUI::TypewriterTick,
            TickInterval, true);
    }
}

// ---------------------------------------------------------------------------
// Navigation
// ---------------------------------------------------------------------------

void UMXRunReportUI::NavigateToSection(int32 SectionIndex)
{
    if (!SectionSwitcher) return;

    const int32 Clamped = FMath::Clamp(SectionIndex, 0, MXReportSection::Count - 1);
    SectionSwitcher->SetActiveWidgetIndex(Clamped);
}

void UMXRunReportUI::ShowFullEventLog(const TArray<FMXEventData>& Events)
{
    if (!FullEventLogScrollBox || !WidgetTree) return;

    FullEventLogScrollBox->ClearChildren();

    for (const FMXEventData& Ev : Events)
    {
        UTextBlock* Line = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
        if (Line)
        {
            Line->SetText(FText::FromString(FString::Printf(
                TEXT("[L%d] %s"), Ev.level_number, *Ev.message_text)));
            FullEventLogScrollBox->AddChild(Line);
        }
    }

    const bool bVisible = (FullEventLogScrollBox->GetVisibility() == ESlateVisibility::Collapsed);
    FullEventLogScrollBox->SetVisibility(bVisible
        ? ESlateVisibility::SelfHitTestInvisible
        : ESlateVisibility::Collapsed);
}

void UMXRunReportUI::ShareReport()
{
    OnShareRequested();
}

// ---------------------------------------------------------------------------
// Card Builders
// ---------------------------------------------------------------------------

UWidget* UMXRunReportUI::BuildAwardCard(const FMXAward& Award)
{
    if (!WidgetTree) return nullptr;

    UBorder* Card = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass());
    if (!Card) return nullptr;

    Card->SetBrushColor(FLinearColor(0.15f, 0.12f, 0.05f, 1.0f));

    UVerticalBox* Inner = WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass());
    if (Inner)
    {
        const UEnum* CatEnum = StaticEnum<EAwardCategory>();
        const FString CatStr = CatEnum
            ? CatEnum->GetNameStringByValue((int64)Award.category)
            : TEXT("Award");

        auto AddLine = [&](const FString& Text, FLinearColor Color = FLinearColor::White)
        {
            UTextBlock* T = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
            if (T)
            {
                T->SetText(FText::FromString(Text));
                T->SetColorAndOpacity(FSlateColor(Color));
                Inner->AddChild(T);
            }
        };

        AddLine(CatStr, FLinearColor(1.0f, 0.85f, 0.3f, 1.0f));
        AddLine(Award.robot_name);
        if (!Award.stat_value.IsEmpty()) AddLine(Award.stat_value, FLinearColor(0.7f, 0.7f, 0.7f, 1.0f));
        if (!Award.narrative.IsEmpty())  AddLine(Award.narrative,  FLinearColor(0.85f, 0.85f, 1.0f, 1.0f));

        Card->SetContent(Inner);
    }

    return Card;
}

UWidget* UMXRunReportUI::BuildDeathCard(const FMXDeathEntry& Entry)
{
    if (!WidgetTree) return nullptr;

    UBorder* Card = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass());
    if (!Card) return nullptr;

    Card->SetBrushColor(FLinearColor(0.1f, 0.03f, 0.03f, 1.0f));

    UVerticalBox* Inner = WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass());
    if (Inner)
    {
        auto AddLine = [&](const FString& Text, FLinearColor Color = FLinearColor::White)
        {
            UTextBlock* T = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
            if (T)
            {
                T->SetText(FText::FromString(Text));
                T->SetColorAndOpacity(FSlateColor(Color));
                Inner->AddChild(T);
            }
        };

        AddLine(FString::Printf(TEXT("%s  Lv.%d"),
                *Entry.robot_profile_snapshot.name,
                Entry.robot_profile_snapshot.level),
            FLinearColor(0.9f, 0.3f, 0.3f, 1.0f));

        AddLine(Entry.death_event.message_text, FLinearColor(0.75f, 0.75f, 0.75f, 1.0f));

        if (!Entry.hat_lost_note.IsEmpty())
        {
            AddLine(Entry.hat_lost_note, FLinearColor(0.9f, 0.6f, 0.0f, 1.0f));
        }

        if (!Entry.eulogy.IsEmpty())
        {
            AddLine(Entry.eulogy, FLinearColor(0.65f, 0.65f, 0.75f, 1.0f));
        }

        Card->SetContent(Inner);
    }

    return Card;
}

UWidget* UMXRunReportUI::BuildSacrificeCard(const FMXSacrificeEntry& Entry)
{
    if (!WidgetTree) return nullptr;

    UBorder* Card = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass());
    if (!Card) return nullptr;

    // Gold border treatment for sacrifices
    Card->SetBrushColor(FLinearColor(0.18f, 0.12f, 0.0f, 1.0f));

    UVerticalBox* Inner = WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass());
    if (Inner)
    {
        auto AddLine = [&](const FString& Text, FLinearColor Color = FLinearColor::White)
        {
            UTextBlock* T = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
            if (T)
            {
                T->SetText(FText::FromString(Text));
                T->SetColorAndOpacity(FSlateColor(Color));
                Inner->AddChild(T);
            }
        };

        AddLine(Entry.robot_profile_snapshot.name, FLinearColor(1.0f, 0.8f, 0.1f, 1.0f));
        AddLine(Entry.sacrifice_event.message_text, FLinearColor(0.8f, 0.8f, 0.8f, 1.0f));

        if (!Entry.robots_saved.IsEmpty())
        {
            const FString Saved = FString::Join(Entry.robots_saved, TEXT(", "));
            AddLine(FString::Printf(TEXT("Saved: %s"), *Saved), FLinearColor(0.3f, 0.9f, 0.4f, 1.0f));
        }

        if (!Entry.extended_narrative.IsEmpty())
        {
            AddLine(Entry.extended_narrative, FLinearColor(0.85f, 0.85f, 1.0f, 1.0f));
        }

        Card->SetContent(Inner);
    }

    return Card;
}

UWidget* UMXRunReportUI::BuildHighlightCard(const FMXHighlight& Highlight)
{
    if (!WidgetTree) return nullptr;

    UBorder* Card = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass());
    if (!Card) return nullptr;

    Card->SetBrushColor(FLinearColor(0.08f, 0.08f, 0.12f, 1.0f));

    UVerticalBox* Inner = WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass());
    if (Inner)
    {
        UTextBlock* MsgText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
        if (MsgText)
        {
            MsgText->SetText(FText::FromString(Highlight.event.message_text));
            Inner->AddChild(MsgText);
        }

        if (!Highlight.narrative.IsEmpty())
        {
            UTextBlock* NarrText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
            if (NarrText)
            {
                NarrText->SetText(FText::FromString(Highlight.narrative));
                NarrText->SetColorAndOpacity(FSlateColor(FLinearColor(0.7f, 0.7f, 0.85f, 1.0f)));
                Inner->AddChild(NarrText);
            }
        }

        Card->SetContent(Inner);
    }

    return Card;
}

UWidget* UMXRunReportUI::BuildLevelCard(int32 LevelNumber, const TArray<FMXEventData>& LevelEvents)
{
    if (!WidgetTree) return nullptr;

    UBorder* Card = WidgetTree->ConstructWidget<UBorder>(UBorder::StaticClass());
    if (!Card) return nullptr;

    Card->SetBrushColor(FLinearColor(0.1f, 0.1f, 0.14f, 1.0f));

    UVerticalBox* Inner = WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass());
    if (Inner)
    {
        // Header row
        UTextBlock* Header = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
        if (Header)
        {
            Header->SetText(FText::FromString(
                FString::Printf(TEXT("Level %d  (%d events)"), LevelNumber, LevelEvents.Num())));
            Inner->AddChild(Header);
        }

        // If expanded, show event summaries
        if (ExpandedLevels.Contains(LevelNumber))
        {
            for (const FMXEventData& Ev : LevelEvents)
            {
                UTextBlock* EvText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
                if (EvText)
                {
                    EvText->SetText(FText::FromString(FString::Printf(TEXT("  • %s"), *Ev.message_text)));
                    EvText->SetColorAndOpacity(FSlateColor(FLinearColor(0.7f, 0.7f, 0.7f, 1.0f)));
                    Inner->AddChild(EvText);
                }
            }
        }

        Card->SetContent(Inner);
    }

    return Card;
}

UWidget* UMXRunReportUI::BuildStatRow(const FString& Label, const FString& Value)
{
    if (!WidgetTree) return nullptr;

    UHorizontalBox* Row = WidgetTree->ConstructWidget<UHorizontalBox>(UHorizontalBox::StaticClass());
    if (!Row) return nullptr;

    UTextBlock* LabelText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
    if (LabelText)
    {
        LabelText->SetText(FText::FromString(Label + TEXT(":")));
        Row->AddChild(LabelText);
    }

    UTextBlock* ValueText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
    if (ValueText)
    {
        ValueText->SetText(FText::FromString(Value));
        Row->AddChild(ValueText);
    }

    return Row;
}

UWidget* UMXRunReportUI::BuildTabButton(int32 SectionIndex, const FString& Label)
{
    if (!WidgetTree) return nullptr;

    UButton* TabBtn = WidgetTree->ConstructWidget<UButton>(UButton::StaticClass());
    if (!TabBtn) return nullptr;

    UTextBlock* BtnText = WidgetTree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass());
    if (BtnText)
    {
        BtnText->SetText(FText::FromString(Label));
        TabBtn->SetContent(BtnText);
    }

    // Bind navigation — capture SectionIndex by value
    TabBtn->OnClicked.AddDynamic(this, &UMXRunReportUI::OnContinueClicked); // placeholder; BP wires real index

    return TabBtn;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

TArray<FMXEventData> UMXRunReportUI::GetLevelEvents(const FMXRunData& RunData, int32 LevelNumber) const
{
    TArray<FMXEventData> Result;
    for (const FMXEventData& Ev : RunData.events)
    {
        if (Ev.level_number == LevelNumber)
        {
            Result.Add(Ev);
        }
    }
    return Result;
}

FString UMXRunReportUI::FormatDuration(float Seconds)
{
    const int32 Total   = FMath::FloorToInt(Seconds);
    const int32 Minutes = Total / 60;
    const int32 Secs    = Total % 60;
    return FString::Printf(TEXT("%dm %ds"), Minutes, Secs);
}

// ---------------------------------------------------------------------------
// Button Callbacks
// ---------------------------------------------------------------------------

void UMXRunReportUI::OnContinueClicked()
{
    // Navigation back to Hub — handled by BP owning widget
    // This stub ensures the binding compiles.
}

void UMXRunReportUI::OnShareClicked()
{
    ShareReport();
}

void UMXRunReportUI::OnFullLogClicked()
{
    ShowFullEventLog(CachedReport.run_data.events);
}
